GET http://localhost:3000/products

###

GET http://localhost:3000/products/f74fb16e-62b2-4af1-abed-1a0516200d1b

###

PATCH http://localhost:3000/products/f74fb16e-62b2-4af1-abed-1a0516200d1b
content-type: application/json

{
    "stock": 5
}

###
POST http://localhost:3000/products
content-type: application/json

{
    "name": "Dinning Bench",
    "price": {
        "amount": 2999.99,
        "currency": "SEK"
    },
    "stock": 1
}